version: "3.8"

services:
  tssk:
    image: timothe/tssk:latest
    container_name: tssk
    environment:
      - CRON=0 2 * * * # every day at 2am
    volumes:
      - /your/local/config/tssk:/app/config
      - /your/local/kometa/config:/config/kometa
    restart: unless-stopped
