sonarr_url: 'http://192.168.0.1:8989'
sonarr_api_key: 'seu_api_sonarr'

skip_unmonitored: true #Ajuste para falso se quiser monitorar também o que não está sendo monitorado pelo Sonarr
utc_offset: +0

################################################################################
##########                     NOVA TEMPORADA EM BREVE                ##########
################################################################################

future_days_new_season: 31

collection_new_season:
  collection_name: "Nova Temporada em Breve"
  smart_label: title.desc
  sort_title: "+1_2Nova Temporada em Breve"
  ignore_blank_results: true

backdrop_new_season:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15

text_new_season:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "Nova Temporada em"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                    NOVA TEMPORADA INICIADA:                ##########
################################################################################

recent_days_new_season_started: 7

collection_new_season_started:
  collection_name: "Nova Temporada Iniciada"
  smart_label: title.desc
  sort_title: "+1_2Nova Temporada Iniciada"
  ignore_blank_results: true

backdrop_new_season_started:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_new_season_started:
  use_text: "Nova Temporada Iniciada"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"
  
################################################################################
##########                         NOVO SERIADO:                      ##########
################################################################################

recent_days_new_show: 7

collection_new_show:
  collection_name: "Adicionado Recentemente"
  smart_label: title.desc
  sort_title: "+1_2Adicionado Recentemente"
  ignore_blank_results: true

backdrop_new_show:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_new_show:
  use_text: "Adicionado Recentemente"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                     PRÓXIMO EPISÓDIO:                      ##########
################################################################################

future_days_upcoming_episode: 31

collection_upcoming_episode:
  collection_name: "Próximo Episódio"
  smart_label: title.desc
  sort_title: "+1_2Próximo Episódio"
  ignore_blank_results: true
  
backdrop_upcoming_episode:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15
  


text_upcoming_episode:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "Próximo Episódio"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"
  
################################################################################
##########                      EPISÓDIO FINAL:                       ##########
################################################################################

future_days_upcoming_finale: 31

collection_upcoming_finale:
  collection_name: "Chegando ao Fim"
  smart_label: title.desc
  sort_title: "+1_2Chegando ao Fim"
  ignore_blank_results: true
  
backdrop_upcoming_finale:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_upcoming_finale:
  date_format: "ddd dd/mm"      # e.g., "yyyy-mm-dd", "mm/dd", "dd/mm", etc.
  capitalize_dates: true
  use_text: "Episódio final"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                           FINALIZADO:                      ##########
################################################################################

collection_ended:
  collection_name: "Seriados Finalizados"
  smart_label: title.desc
  sort_title: "+1_2Seriados Finalizados"
  ignore_blank_results: true

backdrop_ended:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_ended:
  use_text: "F I N A L I Z A D O"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                         RETORNANDO:                         ##########
################################################################################

collection_returning:
  collection_name: "Seriados que Retornarão"
  smart_label: title.desc
  sort_title: "+1_2Seriados que Retornarão"
  ignore_blank_results: true

backdrop_returning:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_returning:
  use_text: "R E T O R N A N D O"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                       FIANAL DE TEMPORADA:                 ##########
################################################################################

recent_days_season_finale: 7

collection_season_finale:
  collection_name: "Final de Temporada"
  smart_label: title.desc
  sort_title: "+1_2Final de Temporada"
  ignore_blank_results: true

backdrop_season_finale:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_season_finale:
  use_text: "Final de Temporada"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"

################################################################################
##########                       EPISÓDIO FINAL:                      ##########
################################################################################

recent_days_final_episode: 7

collection_final_episode:
  collection_name: "Episódio Final"
  smart_label: title.desc
  sort_title: "+1_2Episódio Final"
  ignore_blank_results: true

backdrop_final_episode:
  enable: true
  file: ./config/tssk/overlays/recently_added_vazio.png
  horizontal_align: center
  vertical_align: bottom
  horizontal_offset: 0
  vertical_offset: 15


text_final_episode:
  use_text: "Episódio Final"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 55
  font_size: 60
  #font: Ajuste com a fonte dessejada.
  font_color: "#FFFFFF"