sonarr_url: 'http://192.168.0.1:8989'
sonarr_api_key: 'seu_api_sonarr'

skip_unmonitored: false #Ajuste para falso se quiser monitorar também o que não está sendo monitorado pelo Sonarr
utc_offset: +0

################################################################################
##########                     NOVA TEMPORADA EM BREVE                ##########
################################################################################
#Arquivo: 08_TSSK_TV_NOVA_TEMPORADA_OVERLAYS.yml

future_days_new_season: 31

collection_new_season:
  collection_name: "Nova Temporada em Breve"
  smart_label: title.desc
  sort_title: "+1_2Nova Temporada em Breve"
  ignore_blank_results: true

backdrop_new_season:
  enable: true
  back_color: "#228B22" #VERDE
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0

text_new_season:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NOVA TEMPORADA EM"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" # BRANCO
  
 #font: Ajuste com a fonte dessejada.

################################################################################
##########                    NOVA TEMPORADA INICIADA:                ##########
################################################################################
#Arquivo: 07_TSSK_TV_NOVA_TEMPORADA_INICIADA_OVERLAYS.yml
recent_days_new_season_started: 7

collection_new_season_started:
  collection_name: "Nova Temporada Iniciada"
  smart_label: title.desc
  sort_title: "+1_2Nova Temporada Iniciada"
  ignore_blank_results: true

backdrop_new_season_started:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_season_started:
  use_text: "NOVA TEMPORADA INICIADA"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
  #font: Ajuste com a fonte dessejada.

################################################################################
##########                     PRÓXIMO EPISÓDIO:                      ##########
################################################################################
#Arquivo: 09_TSSK_TV_PROXIMOS_EPISODIOS_OVERLAYS.yml

future_days_upcoming_episode: 31

collection_upcoming_episode:
  collection_name: "Próximo Episódio"
  smart_label: title.desc
  sort_title: "+1_2Próximo Episódio"
  ignore_blank_results: true
  
backdrop_upcoming_episode:
  enable: true
  back_color: "#006580" #AZUL
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0
  


text_upcoming_episode:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "PRÓXIMO EPISÓDIO"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
  #font: Ajuste com a fonte dessejada.
  
################################################################################
##########                     PROXIMO EPISÓDIO FINAL:                ##########
################################################################################
#Arquivo: 10_TSSK_TV_PROXIMOS_FINAIS_OVERLAYS.yml

future_days_upcoming_finale: 31

collection_upcoming_finale:
  collection_name: "Chegando ao Fim"
  smart_label: title.desc
  sort_title: "+1_2Chegando ao Fim"
  ignore_blank_results: true
  
backdrop_upcoming_finale:
  enable: true
  back_color: "#9932CC" #ROXO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_upcoming_finale:
  date_format: "ddd dd/mm"      # e.g., "yyyy-mm-dd", "mm/dd", "dd/mm", etc.
  capitalize_dates: true
  use_text: "EPISÓDIO FINAL"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
  #font: Ajuste com a fonte dessejada.

################################################################################
##########                           FINALIZADO:                      ##########
################################################################################
#Arquivo: 01_TSSK_TV_FINALIZADOS_OVERLAYS.yml

collection_ended:
  collection_name: "Seriados Finalizados"
  smart_label: title.desc
  sort_title: "+1_2Seriados Finalizados"
  ignore_blank_results: true

backdrop_ended:
  enable: true
  back_color: "#000000" #PRETO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_ended:
  use_text: "F I N A L I Z A D O"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 65
  font_color: "#00ff3d" #VERDE
  #font: Ajuste com a fonte dessejada.

################################################################################
##########                         RETORNANDO:                         ##########
################################################################################
#Arquivo: 02_TSSK_TV_RETORNANDO_OVERLAYS.yml

collection_returning:
  collection_name: "Seriados que Retornarão"
  smart_label: title.desc
  sort_title: "+1_2Seriados que Retornarão"
  ignore_blank_results: true

backdrop_returning:
  enable: true
  back_color: "#000000" #PRETO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_returning:
  use_text: "R E T O R N A N D O"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 65
  font_color: "#ff9000" #MOSTARDA
  #font: Ajuste com a fonte dessejada.

################################################################################
##########                       FIANAL DE TEMPORADA:                 ##########
################################################################################
#Arquivo: 11_TSSK_TV_FIM_TEMPORADA_OVERLAYS.yml
recent_days_season_finale: 7

collection_season_finale:
  collection_name: "Final de Temporada"
  smart_label: title.desc
  sort_title: "+1_2Final de Temporada"
  ignore_blank_results: true

backdrop_season_finale:
  enable: true
  back_color: "#ffb902" #AMARELO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_season_finale:
  use_text: "FINAL DE TEMPORADA"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#000000" #PRETO
  #font: Ajuste com a fonte dessejada.

################################################################################
##########                       EPISÓDIO FINAL:                      ##########
################################################################################
#Arquivo: 12_TSSK_TV_EPISODIO_FINAL_OVERLAYS.yml
recent_days_final_episode: 7

collection_final_episode:
  collection_name: "Episódio Final"
  smart_label: title.desc
  sort_title: "+1_2Episódio Final"
  ignore_blank_results: true

backdrop_final_episode:
  enable: true
  back_color: "#ffb902" #MOSTARDA
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_final_episode:
  use_text: "EPISÓDIO FINAL"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#000000" #PRETO
 #font: Ajuste com a fonte dessejada.

 ##DAQUI PRA BAIXO É UTILIZADO O PLEX AO INVÉS DO SONARR PARA CRIAR AS OVERLAYS##  

##NÃO GERAM COLECAO

#################################NIVEL SERIADO#################################

################################################################################
##########                      NOVO EPISÓDIO ADICIONADO:             ##########
################################################################################
#Arquivo: 03_TSSK_TV_NOVO_EPISODIO_OVERLAYS.yml

recent_days_new_episode_added: 7
#create_new_episode_added_overlay_yaml
backdrop_new_episode_added:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_episode_added:
  use_text: "NOVOS EPISÓDIOS"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

################################################################################
##########                      NOVO EPISÓDIO RECENTE ADICIONADO:     ##########
################################################################################
#Arquivo: 04_TSSK_TV_NOVO_RECENTE_EPISODIO_OVERLAYS.yml

recent_days_fresh_espisode_added: 7
#create_recent_new_episode_added_overlay_yaml

backdrop_recent_new_episode_added:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_recent_new_episode_added:
  use_text: "EPISÓDIO NOVO"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

################################################################################
##########                      NOVA TEMPORADA ADICIONADA:            ##########
################################################################################
#Arquivo: 05_TSSK_TV_NOVO_EPISODIO_TEMPORADA_OVERLAYS.yml

recent_days_new_season_added: 7
#create_new_season_added_overlay_yaml
#create_new_season_added_overlay_yaml
backdrop_new_season_added:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_season_added:
  use_text: "TEMPORADA ATUALIZADA"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

################################################################################
##########                         NOVO SERIADO:                      ##########
################################################################################
#Arquivo: 06_TSSK_TV_NOVO_SERIADO_OVERLAYS.yml

recent_days_new_show: 15
#create_new_show_overlay_yaml
backdrop_new_show:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_show:
  use_text: "ADICIONADO RECENTEMENTE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

#############################OVERLAY NIVEL TEMPORADA############################
#############################INSERIDAS NA TEMPORADA#############################

################################################################################
##########                ESPISODIO ADICIONADO A TEMPORADA            ##########
################################################################################
#Arquivo: 13_TSSK_TV_EPISODIO_NA_TEMPORADA_OVERLAYS.yml

recent_days_episode_on_season: 15
#create_episode_on_season_overlay_yaml
backdrop_episode_season:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_episode_season:
  use_text: "NOVOS EPISÓDIOS"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.


################################################################################
##########             ESPISODIO NOVO ADICIONADO A TEMPORADA          ##########
################################################################################
#Arquivo: 14_TSSK_TV_NOVO_EPISODIO_NA_TEMPORADA_OVERLAYS.yml

recent_days_new_episode_on_season: 15
#create_new_episode_on_season_overlay_yaml
backdrop_new_episode_season:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_episode_season:
  use_text: "EPISÓDIO NOVO"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.


################################################################################
##########                      TEMPORADA ADICIONADA                  ##########
################################################################################
#Arquivo: 15_TSSK_TV_TEMPORADA_ADICIONADA_OVERLAYS.yml

recent_days_season_added: 15
#create_season_added_overlay_yaml
backdrop_season_added:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_season_added:
  use_text: "ADICIONADA RECENTEMENTE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

################################################################################
##########                    TEMPORADA RECÉM-LANÇADA                 ##########
################################################################################
#Arquivo: 16_TSSK_TV_NOVA_TEMPORADA_ADICIONADA_OVERLAYS.yml
recent_days_new_season_released: 15
#create_new_season_released_overlay_yaml
backdrop_new_season_released:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_season_released:
  use_text: "NOVA TEMPORADA"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

#############################OVERLAY NIVEL EPISÓDIO############################
#############################INSERIDAS NO EPISÓDIO#############################

################################################################################
##########                       EPISÓDIO ADICIONADO                  ##########
################################################################################
#Arquivo: 17_TSSK_TV_EPISODIO_ADICIONADO_OVERLAYS.yml

recent_days_episode_added: 15
#create_episode_added_overlay_yaml
backdrop_episode_added:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_episode_added:
  use_text: "ADICIONADO RECENTEMENTE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

################################################################################
##########                       EPISÓDIO ADICIONADO                  ##########
################################################################################
#Arquivo: 18_TSSK_TV_NOVO_EPISODIO_ADICIONADO_OVERLAYS.yml

recent_days_new_episode_released: 15
#create_new_episode_released_overlay_yaml
backdrop_new_episode_released:
  enable: true
  back_color: "#EB3233" #VERMELHO
  back_height: 90
  back_width: 1000
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 0


text_new_episode_released:
  use_text: "EPISÓDIO NOVO"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 15
  font_size: 65
  font_color: "#FFFFFF" #BRANCO
#font: Ajuste com a fonte dessejada.

